default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-yalla_development

test:
  <<: *default
  database: rails-yalla_test

production:
  url: <%= ENV['SCALINGO_POSTGRESQL_URL'] %>
