default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-yalla_development

test:
  <<: *default
  database: rails-yalla_test

production:
  <<: *default
  database: rails-yalla_production
  username: rails-yalla
  password: <%= ENV['RAILS_YALLA_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
